name: elevenlabs_phonemes_example
description: Example app for elevenlabs_phonemes Flutter package
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  elevenlabs_phonemes:
    path: ../
  
  rive: ^0.14.0-dev.14

  video_player: ^2.8.6

  circular_reveal_animation: ^2.0.1

  flutter_svg: ^2.0.10

  provider: ^6.1.2
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  supabase_flutter: ^2.8.4
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/charachter.riv
    - assets/charachterv2.riv
    - assets/huda-character.riv
    - assets/callsuccess.riv
    - assets/images/
    - assets/videos/intro_final.mp4

